services:
    - type: web
      name: netra-healthcare-server
      env: node
      buildCommand: npm install && npm run build
      startCommand: npm run build-start
      autoDeploy: true

      # envVars:
      #   - key: NODE_ENV
      #     value: production
      #   - key: DATABASE_URL
      #     sync: false
      #   - key: SUPABASE_DIRECT_URL
      #     sync: false
      #   - key: JWT_SECRET
      #     sync: false
      #   - key: JWT_REFRESH_SECRET
      #     sync: false
      #   - key: JWT_EXPIRES_IN
      #     value: 1d
      #   - key: JWT_REFRESH_EXPIRES_IN
      #     value: 30d
      #   - key: SUPER_ADMIN_EMAIL
      #     sync: false
      #   - key: SUPER_ADMIN_PASSWORD
      #     sync: false
      #   - key: SUPER_ADMIN_NAME
      #     sync: false
